CREATE DATABASE Ejercicio_9;
USE Ejercicio_9;

CREATE TABLE AUTOR(
       Nombre_Autor VARCHAR (100) PRIMARY KEY NOT NULL,
       Nacionalidad VARCHAR (100) NOT NULL,
       Fecha_Nacimiento DATE NOT NULL
);


INSERT INTO AUTOR VALUES('JUNA DEL PATIO','HONDUREÑA','03-01-1980');
INSERT INTO AUTOR VALUES('KERLYN AVALO','HONDUREÑA','06-09-2000');
SELECT *FROM AUTOR;



CREATE TABLE LIBRO(
    Titulo VARCHAR (50) PRIMARY KEY NOT NULL,
    Genero VARCHAR (100) NOT NULL,
    Reseña VARCHAR (100) NOT NULL,
    Texto VARCHAR (100) NOT NULL,
    Fecha DATE NOT NULL,
    Revista VARCHAR (100) NOT NULL
);

INSERT INTO LIBRO VALUES('LA LLANURA SECA','SUSPENSO','BUENA','NO HAY AGUA','20-03-2008','LA LECTURA');
INSERT INTO LIBRO VALUES('LA MONTAÑA TRISTE','SUSPENSO','EXCELENTE','NO HAY ANIMALES','20-01-2020','TIME');
SELECT *FROM LIBRO;

CREATE TABLE ESCRIBE(
    Nombre_Autor VARCHAR (100) FOREIGN KEY REFERENCES AUTOR(Nombre_Autor),
    Titulo VARCHAR (50) FOREIGN KEY REFERENCES LIBRO(Titulo)
);

INSERT INTO ESCRIBE VALUES('JUNA DEL PATIO','LA LLANURA SECA');
INSERT INTO ESCRIBE VALUES('KERLYN AVALO','LA MONTAÑA TRISTE');
SELECT *FROM ESCRIBE;

CREATE TABLE EDICION(
    ISBN VARCHAR (100) PRIMARY KEY NOT NULL,
    Año VARCHAR(150) NOT NULL,
    Idioma VARCHAR(150) NOT NULL,
    Titulo VARCHAR (50) FOREIGN KEY REFERENCES LIBRO(Titulo)
);

INSERT INTO EDICION VALUES('123-456-789','2008','ESPAÑOL','LA LLANURA SECA');
INSERT INTO EDICION VALUES('987-654-321','2021','ESPAÑOL,INGLES','LA MONTAÑA TRISTE');
SELECT *FROM EDICION;

CREATE TABLE COPIA(
   Numero INT PRIMARY KEY NOT NULL,
   ISBN VARCHAR (100) FOREIGN KEY REFERENCES EDICION(ISBN)
);

INSERT INTO COPIA VALUES(1,'123-456-789');
INSERT INTO COPIA VALUES(2,'987-654-321');
SELECT * FROM COPIA;

CREATE TABLE USUARIO(
  DNI VARCHAR (30) PRIMARY KEY NOT NULL,
  Email VARCHAR (100) NOT NULL,
  Nombre VARCHAR (100) NOT NULL,
  Apellido VARCHAR (100) NOT NULL,
);

INSERT INTO USUARIO VALUES('0606199701434','PATRICIO43@GMAIL.COM','PATRICIO','ESTRELLA');
INSERT INTO USUARIO VALUES('0801199874633','SPONGE31@GMAIL.COM','BOB', ' SPONGE');
SELECT * FROM USUARIO;

