CREATE DATABASE Ejercicio_2;
USE Ejercicio_2;

CREATE TABLE DEPARTAMENTO(
    Cod_Departamento VARCHAR (10) PRIMARY KEY NOT NULL,
    Nombre_Departamento VARCHAR (50) 

);

CREATE TABLE MUNICIPIO(
    Cod_Municipio VARCHAR(10) PRIMARY KEY NOT NULL,
    Nombre_Municipio VARCHAR(50) NOT NULL,
    Cod_Departamento VARCHAR (10) FOREIGN KEY REFERENCES DEPARTAMENTO(Cod_Departamento)
);

CREATE TABLE LOCALIDAD(
    Cod_localidad VARCHAR(10) PRIMARY KEY NOT NULL,
    Nombre_localidad VARCHAR (50) NOT NULL,
    Cod_Municipio VARCHAR(10) FOREIGN KEY REFERENCES MUNICIPIO(Cod_Municipio)

);

CREATE TABLE CIUDADANO(
    Id VARCHAR(15) PRIMARY KEY NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Salario VARCHAR(30) NOT NULL,
    Telefono VARCHAR(10) NOT NULL,
    Codigo_localidad VARCHAR (10) FOREIGN KEY REFERENCES LOCALIDAD(Cod_localidad)

);

INSERT INTO DEPARTAMENTO VALUES('06','Choluteca');
INSERT INTO DEPARTAMENTO VALUES('08','Francisco Morazan');

SELECT * FROM DEPARTAMENTO;

INSERT INTO MUNICIPIO VALUES('06','El Triunfo','06');
INSERT INTO MUNICIPIO VALUES('01','Tegucigalpa','08');

SELECT * FROM MUNICIPIO;

INSERT INTO LOCALIDAD VALUES('50','Nance Dulce','06');
INSERT INTO LOCALIDAD VALUES('31','Nueva España','01');

SELECT * FROM LOCALIDAD;

INSERT INTO CIUDADANO VALUES('0606199700000','Pedro Picapiedras','13000','22602514','50');
INSERT INTO CIUDADANO VALUES('0801199512345','Tommy Pickles','28000','22502515','31');

SELECT * FROM CIUDADANO;
