CREATE DATABASE Ejercicio_7;
USE Ejercicio_7;

CREATE TABLE AUTOR(
    Cod_Autor INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR (50)
);
DROP TABLE AUTOR;

INSERT INTO AUTOR VALUES('JUNA DEL PATIO');
INSERT INTO AUTOR VALUES('KERLYN AVALO');
SELECT *FROM AUTOR;

CREATE TABLE LIBRO(
    Cod_Libro VARCHAR(50) PRIMARY KEY NOT NULL,
    Titulo VARCHAR (50) NOT NULL,
    Editorial VARCHAR (100) NOT NULL,
    Num_Paginas INT NOT NULL,
    ISBS VARCHAR (100) NOT NULL
);

INSERT INTO LIBRO VALUES('123456789','LA LLANURA SECA','FONSECA',300,'NO SE QUE ES ESO');
INSERT INTO LIBRO VALUES('122334455','LA MONTAÑA TRISTE','MARTIR',250,'NO SE QUE ES ESO');
SELECT *FROM LIBRO;

CREATE TABLE ESCRIBE(
    Cod_Autor INT FOREIGN KEY REFERENCES AUTOR(Cod_Autor),
    Cod_Libro VARCHAR (50) FOREIGN KEY REFERENCES LIBRO(Cod_Libro)
);

INSERT INTO ESCRIBE VALUES(1,'123456789');
INSERT INTO ESCRIBE VALUES(2,'122334455');
SELECT *FROM ESCRIBE;

CREATE TABLE EJEMPLAR(
    Codigo VARCHAR(50) PRIMARY KEY NOT NULL,
    Localizacion VARCHAR(150) NOT NULL,
    Cod_Libro VARCHAR (50) FOREIGN KEY REFERENCES LIBRO(Cod_Libro)
);

INSERT INTO EJEMPLAR VALUES('1212','LIBROS REVOLUCIONARIOS','123456789');
INSERT INTO EJEMPLAR VALUES('2222','NUEVOS CLASICOS','122334455');
SELECT *FROM EJEMPLAR;

CREATE TABLE USUARIO(
  Cod_Usuario INT PRIMARY KEY IDENTITY(1,1),
  Nombre VARCHAR (50) NOT NULL,
  Direccion VARCHAR (200) NOT NULL,
  Telefono VARCHAR (30)
);

INSERT INTO USUARIO VALUES('PATRICIO ESTRELLA', 'VILLA MARINA',NULL);
INSERT INTO USUARIO VALUES('BOB SPONGE','VILLA MARINA', '555-555-321');
SELECT * FROM USUARIO;

CREATE TABLE PRESTAMO(
    Cod_Usuario INT FOREIGN KEY REFERENCES USUARIO(Cod_Usuario),
    Codigo VARCHAR (50) FOREIGN KEY REFERENCES EJEMPLAR(Codigo)
);

INSERT INTO PRESTAMO VALUES(1,'1212');
INSERT INTO PRESTAMO VALUES(2,'2222');
SELECT * FROM PRESTAMO;