CREATE DATABASE Ejercicio_4;
USE Ejercicio_4;

CREATE TABLE CAMIONERO(
    DNI VARCHAR (15) PRIMARY KEY NOT NULL,
    Nombre VARCHAR (50) NOT NULL,
    Salario MONEY NOT NULL,
    Telefono VARCHAR(20) NOT NULL,
    Direccion VARCHAR(50) NOT NULL
);


INSERT INTO CAMIONERO VALUES('0606197601049','Jesus Alias Chuy','22000.70','22602514','Col. Altos del Cerrito');
INSERT INTO CAMIONERO VALUES('0801197601070','Wilfredo Elvir','26000.10','22702554','Col. Bajos del Cerrito');
SELECT * FROM CAMIONERO;

CREATE TABLE CAMION(
    Matricula VARCHAR (15) PRIMARY KEY NOT NULL,
    Tipo VARCHAR (30) NOT NULL,
    Modelo VARCHAR (30) NOT NULL,
    Potencia VARCHAR (30) NOT NULL
);

INSERT INTO CAMION VALUES('HAL4040','Camion pequeño','H-100','79 ps @ 4000 r.p.m');
INSERT INTO CAMION VALUES('HAJ3131','Camion pequeño','H-100','79 ps @ 4000 r.p.m');
SELECT * FROM CAMION;

CREATE TABLE CONDUCE(
    Cod_Viaje INT PRIMARY KEY IDENTITY(1,1),
    DNI VARCHAR (15) FOREIGN KEY REFERENCES CAMIONERO(DNI),
    Matricula VARCHAR (15) FOREIGN KEY REFERENCES CAMION(Matricula)
);
INSERT INTO CONDUCE VALUES('0606197601049','HAL4040');
INSERT INTO CONDUCE VALUES('0801197601070','HAJ3131');
SELECT * FROM CONDUCE;

CREATE TABLE PAQUETE(
    Cod_Paquete VARCHAR (15) PRIMARY KEY NOT NULL,
    Destinstario VARCHAR (50) NOT NULL,
    Descripcion VARCHAR (200) NOT NULL,
    Direccion_Destinatario VARCHAR (100) NOT NULL,
    DNI VARCHAR (15) FOREIGN KEY REFERENCES CAMIONERO(DNI)
);
INSERT INTO PAQUETE VALUES('HN1520','Kerlyn Avalo','Entrega en correo nacional', 'Col. Nueva Campana', '0606197601049');
INSERT INTO PAQUETE VALUES('HN6034','Marco Polo', 'Bolas pequeña, entrega en casa', 'Col. Arturo Quezada','0801197601070');
SELECT * FROM PAQUETE;

CREATE TABLE DEPARTAMENTO(
    Cod_Departamento VARCHAR (10) PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Cod_Paquete VARCHAR(15) FOREIGN KEY REFERENCES PAQUETE(Cod_Paquete)
);
INSERT INTO DEPARTAMENTO VALUES('06','Choluteca','HN1520');
INSERT INTO DEPARTAMENTO VALUES('08','Francisco Morazan','HN6034');
SELECT * FROM DEPARTAMENTO;