CREATE DATABASE EJERCICIO_11;
USE EJERCICIO_11;

CREATE TABLE PAQUETE_TURISTICO(
    Cod_Paquete INT PRIMARY KEY IDENTITY(1,1),
    Pais VARCHAR(50) NOT NULL,
    Precio MONEY NOT NULL
);

INSERT INTO PAQUETE_TURISTICO VALUES('HONDURAS','8000');
INSERT INTO PAQUETE_TURISTICO VALUES('COSTA RICA','12000');
SELECT * FROM PAQUETE_TURISTICO;

CREATE TABLE AGENCIA(
    Codigo INT PRIMARY KEY IDENTITY(1,1),
    Fecha_Inicio DATE NOT NULL,
    Ciudad VARCHAR (50) NOT NULL,
    Cod_Paquete INT FOREIGN KEY REFERENCES PAQUETE_TURISTICO(Cod_Paquete)
);

INSERT INTO AGENCIA VALUES('10-03-2014','TEGUCIGALPA',1);
INSERT INTO AGENCIA VALUES('22-06-2015','SAN PEDRO SULA',1);
SELECT * FROM AGENCIA;


CREATE TABLE FORMA_DE_PAGO(
    Tipo VARCHAR (50) PRIMARY KEY NOT NULL,
    Monto MONEY NOT NULL
);

INSERT INTO FORMA_DE_PAGO VALUES('EFECTIVO','8000');
INSERT INTO FORMA_DE_PAGO VALUES('TARJETA','12000');
SELECT * FROM FORMA_DE_PAGO;

CREATE TABLE CLIENTE(
    DNI VARCHAR(30) PRIMARY KEY NOT NULL,
    Domicilio VARCHAR (100) NOT NULL,
    Nombre_Apellido VARCHAR (150) NOT NULL,
    Tipo VARCHAR (50) FOREIGN KEY REFERENCES FORMA_DE_PAGO(Tipo)

);

INSERT INTO CLIENTE VALUES('0601-1997-03048','COL. ARTURO QUEZADA','ARMANDO ESTRADA VELASQUEZ','EFECTIVO');
INSERT INTO CLIENTE VALUES('0801-2000-01045','COL. NUEVA ESPAÑA','JUAN PABLO CASCO PINEDA','TARJETA');
SELECT * FROM CLIENTE;

CREATE TABLE COMPRA(
    Codigo_Compra INT PRIMARY KEY IDENTITY(1,1),
    Cod_Paquete INT FOREIGN KEY REFERENCES PAQUETE_TURISTICO(Cod_Paquete),
    DNI VARCHAR (30) FOREIGN KEY REFERENCES CLIENTE(DNI)
);

INSERT INTO COMPRA VALUES(1,'0601-1997-03048');
INSERT INTO COMPRA VALUES(1,'0801-2000-01045');
SELECT * FROM COMPRA;

CREATE TABLE BANCO(
    Nombre VARCHAR(50) PRIMARY KEY NOT NULL,
    Sucursal VARCHAR(50) NOT NULL,
    Tipo VARCHAR (50) FOREIGN KEY REFERENCES FORMA_DE_PAGO(Tipo)
);

INSERT INTO BANCO VALUES('fICOSHA','PRINCIPAL','EFECTIVO');
INSERT INTO BANCO VALUES('BAC','MALL CASCADAS','TARJETA');
SELECT * FROM BANCO;
