CREATE DATABASE Ejercicio_3;
USE Ejercicio_3;

CREATE TABLE CLIENTE(
    Numero_Cliente  INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Telefono VARCHAR(50),
    Domicilio_Legal VARCHAR(50) NOT NULL 
);


INSERT INTO CLIENTE VALUES('Pedro','Parques','22672345','Col. Arturo Paquito');
INSERT INTO CLIENTE VALUES('Juan','Bodoque','33672345','Col. La Montaña');
SELECT * FROM CLIENTE;

CREATE TABLE EVENTO(
    Cod_Evento INT PRIMARY KEY IDENTITY(1,1),
    Descripcion VARCHAR(300) NOT NULL,
    Precentador VARCHAR(50) NOT NULL,
    Pecio INT NOT NULL,
    Horario VARCHAR(20)  NOT NULL,
    Conjunto_Animadores VARCHAR (200) NOT NULL
);

INSERT INTO EVENTO VALUES('Inauguracion de escuela','Patricio Estrella','5000','9:00AM-12:00PM','Bailarines');
INSERT INTO EVENTO VALUES('Fiesta de cumpleaños','Bob Esponja','3500','2:00PM-5:00PM','Payasos');
SELECT * FROM EVENTO;
DROP table evento;

CREATE TABLE CONTRATA(
    Numero_Cliente INT FOREIGN KEY REFERENCES CLIENTE(Numero_Cliente),
    Cod_Evento  INT FOREIGN KEY REFERENCES EVENTO(Cod_Evento)
);
INSERT INTO CONTRATA VALUES(1,1);
INSERT INTO CONTRATA VALUES(2,1);
SELECT * FROM CONTRATA;

CREATE TABLE PRECENTADOR(
    Cod_Precentador INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR (50) NOT NULL,
    Apellido VARCHAR (50) NOT NULL,
    Año_Comienzo DATE NOT NULL,
    Tipo_Evento VARCHAR(200) NOT NULL,
    Dni VARCHAR (30) NOT NULL,
    Cod_Evento INT FOREIGN KEY REFERENCES EVENTO(Cod_Evento)
    
);

INSERT INTO PRECENTADOR VALUES('Calamardo','Tentacuos','2001','Animador','0606198420934',1);
INSERT INTO PRECENTADOR VALUES('Francisco','Sanchez','2018','Animador','08011200293958',2);
SELECT * FROM PRECENTADOR;


CREATE TABLE DISFRAZ(
    Cod_Disfraz INT PRIMARY KEY IDENTITY(1,1),
    Personaje VARCHAR(50) NOT NULL,
    Precio_Alquiler INT NOT NULL
);


INSERT INTO DISFRAZ VALUES('Payaso','100');
INSERT INTO DISFRAZ VALUES('Policia','180');
SELECT * FROM DISFRAZ;


CREATE TABLE ANIMADOR(
    Cod_Animador INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR (50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Dni VARCHAR (30) NOT NULL,
    Cod_Disfraz INT FOREIGN KEY REFERENCES DISFRAZ(Cod_Disfraz)

);

INSERT INTO ANIMADOR VALUES('Pedro','Picapiedras','0606199943434',1);
INSERT INTO ANIMADOR VALUES('Francisco','Sanchez','0606198928080',2);
SELECT * FROM ANIMADOR;

CREATE TABLE PARTICIPAN(
    Cod_Evento INT FOREIGN KEY REFERENCES EVENTO(Cod_Evento),
    Cod_Animador INT FOREIGN KEY REFERENCES ANIMADOR(Cod_Animador)
);

INSERT INTO PARTICIPAN VALUES(1,1);
INSERT INTO PARTICIPAN VALUES(1,1);
SELECT * FROM PARTICIPAN;
